name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@v1
    - name: Build and test
      run: |
          swift package init
          swift package generate-xcodeproj 
          swift build -v 
          swift test -v
